CREATE TABLE `custom_characters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(128) NOT NULL,
	`title` varchar(256) DEFAULT '',
	`player` varchar(128) DEFAULT '',
	`race` varchar(64) NOT NULL,
	`className` varchar(64) NOT NULL,
	`subclass` varchar(128) DEFAULT '',
	`level` int NOT NULL DEFAULT 1,
	`age` int DEFAULT 0,
	`alignment` varchar(64) DEFAULT '',
	`background` varchar(128) DEFAULT '',
	`proficiencyBonus` int NOT NULL DEFAULT 2,
	`armorClass` int NOT NULL DEFAULT 10,
	`acDescription` varchar(256) DEFAULT '',
	`initiative` int DEFAULT 0,
	`speed` int DEFAULT 9,
	`hitPoints` int NOT NULL DEFAULT 10,
	`hitDice` varchar(32) DEFAULT '1d10',
	`attributes` json NOT NULL,
	`savingThrows` json,
	`skills` json,
	`attacks` json,
	`features` json,
	`proficiencies` json,
	`spellcasting` json,
	`equipment` json,
	`personality` text,
	`ideals` text,
	`bonds` text,
	`flaws` text,
	`description` text,
	`essence` text,
	`quote` text,
	`artUrl` text,
	`accentColor` varchar(32) DEFAULT '#c9a84c',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `custom_characters_id` PRIMARY KEY(`id`)
);
